file:
  separator: /
ploot: false
collapse-enchantments: false
max-lenght-per-line: 50
describe-enchantments: false
enchantments-position: 1 # bottom
force-collapse-enchantments: false
show-enchants: false
add-lines-top-enchants:
- ''
- '<#717171> ⚛ Encantamientos (#current#/10):'
debug:
  LOREPARSER: false
  ANVILREPAIR: true
  INFO: false
  WARNING: false
  DEBUG: false
  ERROR: false
  DEPENDECY: true
  MODIFYLEVEL: false
  IREPLACER: true
IReplacer:
  #Not enabled
  Pickup-Event-Enabled: true
  Click-Event-Enabled: true
  Smithing-Event-Enabled: false
  Crafting-Event-Enabled: true
  InventoryOpen-Event-Enabled: true
  Furnace-Event-Enabled: true
  InventoryMove-Event-Enabled: true
modules:
  custom-lore: true
  #Any other module dont work for this build
mode:
  api: true

colorcode:
  RARE: '<#FFF999>'