#generate plugin.yml
name: Realmcraft
main: dev.arubik.realmcraft.realmcraft
version: 1.0.0
api-version: 1.16
author: arubik
description: A minecraft plugin for the realmcraft server
loadbefore:
  - "PacketUpgrades"
  - "MMOItems"
  - 'gpttalk'
depend:
  - "MythicLib"